# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cinst pandoc
  - ps: $env:Path += ";C:\Program Files\Pandoc\"

cache:
  - C:\RLibrary
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\Pandoc\

# Adapt as necessary starting from here
environment:
  matrix:
    - R_VERSION: stable
      R_ARCH: x64
      GCC_PATH: mingw_64
      CRAN: https://cran.rstudio.com

platform: x64

build_script:
  - pandoc -v
  - travis-tool.sh install_deps
  - Rscript.exe --verbose ./pkgdown/build-site.R

test_script:
  - travis-tool.sh run_tests

on_finish:
  - bash.exe ./pkgdown/deploy.sh

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
